export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';
export const REQUEST_MOVIES = 'REQUEST_MOVIES';
export const SHOW_MOVIES = 'SHOW_MOVIES';
export const SORT_MOVIES_BY_DATE = 'SORT_MOVIES_BY_DATE';
export const SORT_MOVIES_BY_RATE = 'SORT_MOVIES_BY_RATE';